wipes_reviews <- read.csv("E:\\Drexel\\Course-Study\\Fall 2016 Sep19-Dec10\\BUSN-710\\Dows-Project\\wipes_reviews.csv")


Reviews_new <- wipes_reviews[which(wipes_reviews$Agg_Item_Market_Category !='Personal' & 
                               wipes_reviews$Agg_Item_Market_Category != 'Home'), ]


Reviews_new[grep("allpurpose",tolower(Reviews_new$Text)),"Agg_Agg_Item_Market_Category"]='Home'
Reviews_new[grep("appliance",tolower(Reviews_new$Text)),"Agg_Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("auto",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("automotive",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("bathroom",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("car",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("carpet",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("cleaning",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("computer",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("disinfecting",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("dust",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("duster",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("electronic",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("floor",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("floormate",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("furniture",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("glass",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("hard wood",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("headlight",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("home",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("household",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("interior",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("leather",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("lysol disinfecting",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("monitor",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("multisurface",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("multiuse",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("pet",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("puppy",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("screen",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("seat belt",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("silver",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("steel",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("suede",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("surface",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("toilet",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'
Reviews_new[grep("bathtub",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Home'


Reviews_new[grep("baby",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Personal'
Reviews_new[grep("wipe",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Personal'
Reviews_new[grep("makeup",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Personal'
Reviews_new[grep("remover",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Personal'
Reviews_new[grep("antibacterial",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]= 'Personal'
Reviews_new[grep("hand wipe",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("face wipe",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("antibacterial",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("hand",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("boogie wipe",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("baby",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("hand",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("face",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("hand face",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("makeup",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("facial",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("stuffy nose",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("first aid",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("saline",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("huggies",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("cat",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("dermapet",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("dog",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("medicated",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("dude",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("flushable",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("shoe",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("purse",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("diaper",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("flannel", tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("breast",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("nose",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("breastpump",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("tooth",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("retainer",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("mouth",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("guard",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("skin",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("rash",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("acne",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("dental",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("pampers",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("lens",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("jewelry",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("Sephora",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("germx",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("bathing",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("pacifier",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("mask",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("sofetch",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'
Reviews_new[grep("waterwipe",tolower(Reviews_new$Text)),"Agg_Item_Market_Category"]='Personal'

df<- sqldf("select * from Reviews_new where Agg_Item_Market_Category='Home'")


